# coding: utf-8

name: test-workflow

run-name: test-workflow trigged ${{github.actor}}

on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: test workflow
        run: |
          sudo apt-get update
          sudo curl -sSL https://install.python-poetry.org | python3 -
          poetry config virtualenvs.in-project true
          poetry install
          export PATH="/app/.venv/bin:$PATH"
          python -m spacy download en_core_web_sm
          python -m spacy download fr_core_news_sm
          python -m nltk.downloader punkt
          make test
